rootdir = Dir.pwd

task :configure do
  cd rootdir
  sh "make -C #{rootdir}/squashfs_compressor configure"
  sh "cd #{rootdir}/yaml; ./configure"
end

task :all do
  cd rootdir
  sh "make -C #{rootdir}/rb_tree lib"
  sh "make -C #{rootdir}/squashfs_compressor lib"
  sh "make -C #{rootdir}/yaml; mv #{rootdir}/yaml/src/.libs/libyaml.a #{rootdir}/yaml/libyamlaxfs.a"
end

task :clobber do
  cd rootdir
  sh "make -C #{rootdir}/squashfs_compressor clobber"
  sh "make -C #{rootdir}/rb_tree clobber"
  if File.exists?("#{rootdir}/yaml/Makefile")
    sh "make -C #{rootdir}/yaml distclean"
    rm_rf "#{rootdir}/yaml/libyamlaxfs.a"
  end
end

task :clean => :clobber

task :default => :all
